In [4]:

import pandas as pd
from io import StringIO
import json
import dash
from dash import html, dcc, dash_table
import plotly.express as px
from dash.dependencies import Input, Output
from itables import show

In [ ]:
price_cols = ["bid_price_1", "bid_price_2", "bid_price_3", "ask_price_1", "ask_price_2", "ask_price_3"]
volume_cols = ["bid_volume_1", "bid_volume_2", "bid_volume_3", "ask_volume_1", "ask_volume_2", "ask_volume_3"]

def outlier_remover(row):
    if pd.notna(row["bid_price_3"]):
        row["maker_bid_price_1"], row["maker_bid_volume_1"] = row["bid_price_2"], row["bid_volume_2"]
        row["maker_bid_price_2"], row["maker_bid_volume_2"] = row["bid_price_3"], row["bid_volume_3"]
    else:
        row["maker_bid_price_1"], row["maker_bid_volume_1"] = row["bid_price_1"], row["bid_volume_1"]
        row["maker_bid_price_2"], row["maker_bid_volume_2"] = row["bid_price_2"], row["bid_volume_2"]
    if pd.notna(row["ask_price_3"]):
        row["maker_ask_price_1"], row["maker_ask_volume_1"] = row["ask_price_2"], row["ask_volume_2"]
        row["maker_ask_price_2"], row["maker_ask_volume_2"] = row["ask_price_3"], row["ask_volume_3"]
    else:
        row["maker_ask_price_1"], row["maker_ask_volume_1"] = row["ask_price_1"], row["ask_volume_1"]
        row["maker_ask_price_2"], row["maker_ask_volume_2"] = row["ask_price_2"], row["ask_volume_2"]
        

    return row
#If using log data use this, make sure to change filename here and add file to current folder

with open("27173.log") as file:
    json_data = json.load(file)
prices = pd.read_csv("prices_round_0_day_-1.csv", sep=';')
trades = pd.read_csv("trades_round_0_day_-1.csv", sep=';')

#If using data from datapacket off website use this
#prices = pd.read_csv(StringIO(json_data["activitiesLog"]), sep=';')
#trades = pd.DataFrame(json_data["tradeHistory"])

trades["our_direction"]=trades.apply(lambda row: "buy" if row["buyer"]=="SUBMISSION" else "sell" if row["seller"]=="SUBMISSION" else "bot_trade", axis=1) 
trades["buyer"] = trades["buyer"].fillna("")
trades["seller"] = trades["seller"].fillna("")

eme_prices = prices[prices["product"]=="EMERALDS"]
tom_prices = prices[prices["product"]=="TOMATOES"]

eme_trades = trades[trades["symbol"]=="EMERALDS"]
tom_trades = trades[trades["symbol"]=="TOMATOES"]

#fair value line, calculated by 
tom_prices=tom_prices.apply(outlier_remover, axis=1)
eme_prices=eme_prices.apply(outlier_remover, axis=1)
tom_prices["fair_value"]=(tom_prices["maker_bid_price_1"]+tom_prices["maker_bid_price_2"]+tom_prices["maker_ask_price_1"]+tom_prices["maker_ask_price_2"])/4
eme_prices["fair_value"]=(eme_prices["maker_bid_price_1"]+eme_prices["maker_bid_price_2"]+eme_prices["maker_ask_price_1"]+eme_prices["maker_ask_price_2"])/4

#changes prices data into long format
def longDF(df):
    quotes=[]
    for p_col, v_col in zip(price_cols, volume_cols):
        data = df[["timestamp"]].copy()
        data["price"] = df[p_col].values
        data["volume"] = df[v_col].values
        if "bid" in p_col:
            data["side"] = "bid"
        if "ask" in p_col:
            data["side"] = "ask"
        data["fair_value"]=df["fair_value"].values
        quotes.append(data)
    return pd.concat(quotes, ignore_index=True)

tom_long=longDF(tom_prices)
tom_long.dropna(inplace=True)
eme_long=longDF(eme_prices)
eme_long.dropna(inplace=True)

symbol_map= {"buy": "triangle-up", "sell": "triangle-down", "bot_trade": "star"}
datasets = {"EMERALDS": (eme_long, eme_trades), "TOMATOES": (tom_long, tom_trades)}

#calculate position
dir_map = {"buy": 1, "sell": -1, "bot_trade": 0}
tom_trades["position"]=(tom_trades["quantity"] * tom_trades["our_direction"].map(dir_map)).cumsum()
eme_trades["position"]=(eme_trades["quantity"] * eme_trades["our_direction"].map(dir_map)).cumsum()

#generates scatter plot graphs
def make_figure(ticker):
    prices, trades = datasets[ticker]
    figure=px.scatter(prices, x="timestamp", y="price", size="volume", color="side")
    figure.add_scatter(x=trades["timestamp"], y=trades["price"], mode="markers", name="trades",
                       customdata=trades[["timestamp","quantity", "buyer", "seller", "position"]].values,
                       hovertemplate="timestamp=%{x}<br>price=%{y}<br>volume=%{customdata[1]}<br>buyer=%{customdata[2]}<br>seller=%{customdata[3]}<br>our_position=%{customdata[4]}<extra></extra>",
                       marker_symbol=trades["our_direction"].map(symbol_map), marker_size=20, marker_color="black")
    figure.add_scatter(x=prices["timestamp"], y=prices["fair_value"], mode="markers", name="fair value")
    return figure



#generates interactive tool
def grapher():
    app = dash.Dash(__name__)
    
    app.layout = html.Div([
        dcc.Dropdown(id="ticker_dropdown", options=[{"label": x, "value": x} for x in datasets.keys()],
                     value="EMERALDS"),
        dcc.Graph(id="main_graph"),
    ])
    @app.callback(
        Output("main_graph", "figure"),
        Input("ticker_dropdown", "value"))
    def update_graph(selected_ticker):
        return make_figure(selected_ticker)
    
    app.run(debug=True)
grapher()

In [89]:

tom_trades.head(60)

,timestamp,buyer,seller,symbol,currency,price,quantity,our_direction,position
0,2900,SUBMISSION,,TOMATOES,XIRECS,4998.0,3,buy,3
1,3300,SUBMISSION,,TOMATOES,XIRECS,4997.0,3,buy,6
2,3900,,SUBMISSION,TOMATOES,XIRECS,5002.0,6,sell,0
3,4200,SUBMISSION,,TOMATOES,XIRECS,5001.0,7,buy,7
7,10200,,SUBMISSION,TOMATOES,XIRECS,5014.0,2,sell,5
9,12900,SUBMISSION,,TOMATOES,XIRECS,5003.0,11,buy,16
10,13200,,SUBMISSION,TOMATOES,XIRECS,5010.0,5,sell,11
11,14700,,SUBMISSION,TOMATOES,XIRECS,5009.0,3,sell,8
12,14800,SUBMISSION,,TOMATOES,XIRECS,4997.0,5,buy,13
13,15100,SUBMISSION,,TOMATOES,XIRECS,5002.0,7,buy,20
14,17200,SUBMISSION,,TOMATOES,XIRECS,5001.0,10,buy,30
15,17400,,SUBMISSION,TOMATOES,XIRECS,5009.0,5,sell,25
16,18800,,SUBMISSION,TOMATOES,XIRECS,5005.0,5,sell,20
17,21400,SUBMISSION,,TOMATOES,XIRECS,4997.0,9,buy,29
18,23400,,SUBMISSION,TOMATOES,XIRECS,4996.0,5,sell,24
20,24600,SUBMISSION,,TOMATOES,XIRECS,4989.0,2,buy,26
21,25100,SUBMISSION,,TOMATOES,XIRECS,4994.0,5,buy,31
22,27300,SUBMISSION,,TOMATOES,XIRECS,4993.0,5,buy,36
23,27300,,,TOMATOES,XIRECS,4993.0,5,bot_trade,36
27,30900,SUBMISSION,,TOMATOES,XIRECS,4983.0,5,buy,41
29,33500,,SUBMISSION,TOMATOES,XIRECS,4992.0,5,sell,36
32,38300,SUBMISSION,,TOMATOES,XIRECS,4987.0,6,buy,42
34,40000,,SUBMISSION,TOMATOES,XIRECS,4991.0,3,sell,39
38,42900,,SUBMISSION,TOMATOES,XIRECS,4983.0,12,sell,27
40,44300,SUBMISSION,,TOMATOES,XIRECS,4979.0,2,buy,29
41,45700,SUBMISSION,,TOMATOES,XIRECS,4982.0,12,buy,41
42,48000,,SUBMISSION,TOMATOES,XIRECS,4990.0,5,sell,36
43,48700,,SUBMISSION,TOMATOES,XIRECS,4994.0,2,sell,34
45,51100,,SUBMISSION,TOMATOES,XIRECS,4987.0,6,sell,28
46,51500,SUBMISSION,,TOMATOES,XIRECS,4986.0,11,buy,39
47,52200,,SUBMISSION,TOMATOES,XIRECS,4992.0,3,sell,36
48,54700,SUBMISSION,,TOMATOES,XIRECS,4989.0,5,buy,41
52,58600,SUBMISSION,,TOMATOES,XIRECS,4986.0,7,buy,48
53,58800,,SUBMISSION,TOMATOES,XIRECS,4993.0,4,sell,44
54,59300,SUBMISSION,,TOMATOES,XIRECS,4984.0,5,buy,49
55,59300,,,TOMATOES,XIRECS,4984.0,2,bot_trade,49
56,59400,,SUBMISSION,TOMATOES,XIRECS,4991.0,4,sell,45
58,59800,SUBMISSION,,TOMATOES,XIRECS,4986.0,11,buy,56
62,65300,SUBMISSION,,TOMATOES,XIRECS,4984.0,5,buy,61
63,65600,,SUBMISSION,TOMATOES,XIRECS,4990.0,9,sell,52
64,66200,,SUBMISSION,TOMATOES,XIRECS,4989.0,11,sell,41
65,66600,SUBMISSION,,TOMATOES,XIRECS,4982.0,5,buy,46
66,67700,SUBMISSION,,TOMATOES,XIRECS,4981.0,5,buy,51
67,68600,,SUBMISSION,TOMATOES,XIRECS,4987.0,7,sell,44
69,70300,,SUBMISSION,TOMATOES,XIRECS,4988.0,8,sell,36
70,73300,,SUBMISSION,TOMATOES,XIRECS,4989.0,8,sell,28
71,73500,,SUBMISSION,TOMATOES,XIRECS,4989.0,10,sell,18
72,75000,,SUBMISSION,TOMATOES,XIRECS,4996.0,2,sell,16
73,75600,SUBMISSION,,TOMATOES,XIRECS,4987.0,6,buy,22
74,78000,SUBMISSION,,TOMATOES,XIRECS,4990.0,10,buy,32
76,82800,,SUBMISSION,TOMATOES,XIRECS,4989.0,5,sell,27
77,83600,SUBMISSION,,TOMATOES,XIRECS,4981.0,4,buy,31
79,85400,SUBMISSION,,TOMATOES,XIRECS,4978.0,3,buy,34
80,86900,SUBMISSION,,TOMATOES,XIRECS,4978.0,4,buy,38
81,89300,,SUBMISSION,TOMATOES,XIRECS,4987.0,2,sell,36
82,89400,SUBMISSION,,TOMATOES,XIRECS,4980.0,11,buy,47
85,91300,,SUBMISSION,TOMATOES,XIRECS,4986.0,5,sell,42
87,95600,,SUBMISSION,TOMATOES,XIRECS,4983.0,6,sell,36
88,96100,,SUBMISSION,TOMATOES,XIRECS,4989.0,4,sell,32
89,96400,,SUBMISSION,TOMATOES,XIRECS,4989.0,4,sell,28

In [51]:
price_cols = ["bid_price_1", "bid_price_2", "bid_price_3", "ask_price_1", "ask_price_2", "ask_price_3"]
volume_cols = ["bid_volume_1", "bid_volume_2", "bid_volume_3", "ask_volume_1", "ask_volume_2", "ask_volume_3"]


#If using log data use this, make sure to change filename here and add file to current folder

with open("19174.log") as file:
    json_data = json.load(file)
#prices = pd.read_csv("prices_round_0_day_-1.csv", sep=';')
#trades = pd.read_csv("trades_round_0_day_-1.csv", sep=';')

#If using data from datapacket off website use this
prices = pd.read_csv(StringIO(json_data["activitiesLog"]), sep=';')
trades = pd.DataFrame(json_data["tradeHistory"])

trades["our_direction"]=trades.apply(lambda row: "buy" if row["buyer"]=="SUBMISSION" else "sell" if row["seller"]=="SUBMISSION" else "bot_trade", axis=1) 
trades["buyer"] = trades["buyer"].fillna("")
trades["seller"] = trades["seller"].fillna("")

eme_prices = prices[prices["product"]=="EMERALDS"]
tom_prices = prices[prices["product"]=="TOMATOES"]

eme_trades = trades[trades["symbol"]=="EMERALDS"]
tom_trades = trades[trades["symbol"]=="TOMATOES"]
tom_prices["profit_and_loss"]+=5013
tom_prices=tom_prices.apply(outlier_remover, axis=1)
tom_prices["fair_value_diff_1"]=(tom_prices["profit_and_loss"]-(tom_prices["maker_bid_price_1"]*tom_prices["maker_bid_volume_1"]+tom_prices["maker_bid_price_2"]*tom_prices["maker_bid_volume_2"]+tom_prices["maker_ask_price_1"]*tom_prices["maker_ask_volume_1"]+tom_prices["maker_ask_price_2"]*tom_prices["maker_ask_volume_2"])/(tom_prices["maker_bid_volume_1"]+tom_prices["maker_bid_volume_2"]+tom_prices["maker_ask_volume_1"]+tom_prices["maker_ask_volume_2"]))**2
tom_prices["fair_value_diff_2"]=(tom_prices["profit_and_loss"]-(tom_prices["maker_bid_price_1"]+tom_prices["maker_bid_price_2"]+tom_prices["maker_ask_price_1"]+tom_prices["maker_ask_price_2"])/4)**2

print(tom_prices["fair_value_diff_1"].sum(), tom_prices["fair_value_diff_2"].sum())
tom_prices.head(50)

C:\Users\malac\AppData\Local\Temp\ipykernel_23140\1744533167.py:25: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

126.05290880508366 85.93336319923401

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,...,maker_bid_price_1,maker_bid_volume_1,maker_bid_price_2,maker_bid_volume_2,maker_ask_price_1,maker_ask_volume_1,maker_ask_price_2,maker_ask_volume_2,fair_value_diff_1,fair_value_diff_2
0,-1,0,TOMATOES,4999,6,4998,19,NaN,NaN,5013,...,4999,6,4998.0,19.0,5013,6,5014.0,19.0,49.000000,49.000000
3,-1,100,TOMATOES,5000,5,4998,23,NaN,NaN,5013,...,5000,5,4998.0,23.0,5013,5,5014.0,23.0,0.047669,0.003320
5,-1,200,TOMATOES,5000,10,4999,20,NaN,NaN,5013,...,5000,10,4999.0,20.0,5013,10,5015.0,20.0,0.024211,0.005222
6,-1,300,TOMATOES,5000,9,4999,24,NaN,NaN,5014,...,5000,9,4999.0,24.0,5014,9,5015.0,24.0,0.038914,0.038914
8,-1,400,TOMATOES,5000,6,4999,25,NaN,NaN,5014,...,5000,6,4999.0,25.0,5014,6,5015.0,25.0,0.059366,0.059366
11,-1,500,TOMATOES,5000,6,4999,25,NaN,NaN,5014,...,5000,6,4999.0,25.0,5014,6,5015.0,25.0,0.012944,0.012944
13,-1,600,TOMATOES,5000,9,4999,17,NaN,NaN,5014,...,5000,9,4999.0,17.0,5014,9,5015.0,17.0,0.037956,0.037956
14,-1,700,TOMATOES,5000,5,4999,24,NaN,NaN,5014,...,5000,5,4999.0,24.0,5014,5,5015.0,24.0,0.026438,0.026438
16,-1,800,TOMATOES,5000,5,4998,25,NaN,NaN,5013,...,5000,5,4998.0,25.0,5013,5,5014.0,25.0,0.074324,0.011227
19,-1,900,TOMATOES,5000,9,4998,15,NaN,NaN,5013,...,5000,9,4998.0,15.0,5013,9,5015.0,15.0,0.000086,0.000086
21,-1,1000,TOMATOES,5000,7,4999,17,NaN,NaN,5014,...,5000,7,4999.0,17.0,5014,7,5015.0,17.0,0.029709,0.029709
22,-1,1100,TOMATOES,5000,7,4999,15,NaN,NaN,5013,...,5000,7,4999.0,15.0,5013,7,5015.0,15.0,0.039142,0.011435
24,-1,1200,TOMATOES,5000,5,4999,21,NaN,NaN,5014,...,5000,5,4999.0,21.0,5014,5,5015.0,21.0,0.025183,0.025183
27,-1,1300,TOMATOES,5001,10,5000,21,NaN,NaN,5014,...,5001,10,5000.0,21.0,5014,10,5016.0,21.0,0.028161,0.006257
29,-1,1400,TOMATOES,5000,7,4999,19,NaN,NaN,5014,...,5000,7,4999.0,19.0,5014,7,5015.0,19.0,0.032112,0.032112
30,-1,1500,TOMATOES,5000,5,4999,21,NaN,NaN,5014,...,5000,5,4999.0,21.0,5014,5,5015.0,21.0,0.014782,0.014782
32,-1,1600,TOMATOES,5001,7,4999,24,NaN,NaN,5014,...,5001,7,4999.0,24.0,5014,7,5015.0,24.0,0.102842,0.033707
35,-1,1700,TOMATOES,5000,10,4999,16,NaN,NaN,5014,...,5000,10,4999.0,16.0,5014,10,5015.0,16.0,0.024414,0.024414
37,-1,1800,TOMATOES,5000,10,4998,15,NaN,NaN,5013,...,5000,10,4998.0,15.0,5013,10,5014.0,15.0,0.030625,0.015625
38,-1,1900,TOMATOES,5000,9,4999,23,NaN,NaN,5013,...,5000,9,4999.0,23.0,5013,9,5015.0,23.0,0.039494,0.007984
40,-1,2000,TOMATOES,4999,10,4998,25,NaN,NaN,5013,...,4999,10,4998.0,25.0,5013,10,5014.0,25.0,0.026121,0.026121
43,-1,2100,TOMATOES,4999,8,4997,23,NaN,NaN,5012,...,4999,8,4997.0,23.0,5012,8,5013.0,23.0,0.066402,0.018692
45,-1,2200,TOMATOES,4997,6,4996,16,NaN,NaN,5011,...,4997,6,4996.0,16.0,5011,6,5012.0,16.0,0.005013,0.005013
46,-1,2300,TOMATOES,4997,6,4995,22,NaN,NaN,5010,...,4997,6,4995.0,22.0,5010,6,5011.0,22.0,0.038831,0.002938
48,-1,2400,TOMATOES,4996,7,4995,20,NaN,NaN,5010,...,4996,7,4995.0,20.0,5010,7,5011.0,20.0,0.005877,0.005877
51,-1,2500,TOMATOES,4996,7,4995,16,NaN,NaN,5009,...,4996,7,4995.0,16.0,5009,7,5011.0,16.0,0.035037,0.007984
53,-1,2600,TOMATOES,4996,9,4995,21,NaN,NaN,5009,...,4996,9,4995.0,21.0,5009,9,5011.0,21.0,0.048237,0.014311
54,-1,2700,TOMATOES,4997,10,4995,21,NaN,NaN,5010,...,4997,10,4995.0,21.0,5010,10,5011.0,21.0,0.089204,0.044084
56,-1,2800,TOMATOES,4997,5,4996,24,NaN,NaN,5011,...,4997,5,4996.0,24.0,5011,5,5012.0,24.0,0.000326,0.000326
59,-1,2900,TOMATOES,4997,7,4996,19,NaN,NaN,5011,...,4997,7,4996.0,19.0,5011,7,5012.0,19.0,0.039688,0.039688
61,-1,3000,TOMATOES,4996,7,4995,18,NaN,NaN,5010,...,4996,7,4995.0,18.0,5010,7,5011.0,18.0,0.037388,0.037388
62,-1,3100,TOMATOES,4996,8,4995,18,NaN,NaN,5010,...,4996,8,4995.0,18.0,5010,8,5011.0,18.0,0.009347,0.009347
64,-1,3200,TOMATOES,4996,7,4995,21,NaN,NaN,5009,...,4996,7,4995.0,21.0,5009,7,5011.0,21.0,0.080481,0.025183
67,-1,3300,TOMATOES,4996,5,4995,22,NaN,NaN,5010,...,4996,5,4995.0,22.0,5010,5,5011.0,22.0,0.001603,0.001603
69,-1,3400,TOMATOES,4996,7,4994,19,NaN,NaN,5009,...,4996,7,4994.0,19.0,5009,7,5011.0,19.0,0.000004,0.000004
70,-1,3500,TOMATOES,4995,7,4993,16,NaN,NaN,5008,...,4995,7,4993.0,16.0,5008,7,5009.0,16.0,0.014469,0.000504
72,-1,3600,TOMATOES,4995,7,4993,16,NaN,NaN,5008,...,4995,7,4993.0,16.0,5008,7,5009.0,16.0,0.095335,0.044495
75,-1,3700,TOMATOES,4995,7,4994,23,NaN,NaN,5002,...,4995,7,4994.0,23.0,5008,7,5010.0,23.0,0.081611,0.023209
77,-1,3800,TOMATOES,4994,7,4993,20,NaN,NaN,5008,...,4994,7,4993.0,20.0,5008,7,5009.0,20.0,0.021458,0.021458
78,-1,3900,TOMATOES,5002,8,4995,5,4994.0,16.0,5009,...,4995,5,4994.0,16.0,5009,5,5010.0,16.0,0.055851,0.055851
81,-1,4000,TOMATOES,4996,8,4994,22,NaN,NaN,5009,...,4996,8,4994.0,22.0,5009,8,5010.0,22.0,0.029866,0.003153
82,-1,4100,TOMATOES,4996,6,4994,19,NaN,NaN,5009,...,4996,6,4994.0,19.0,5009,6,5010.0,19.0,0.133125,0.055161
85,-1,4200,TOMATOES,4996,8,4994,15,NaN,NaN,5001,...,4996,8,4994.0,15.0,5009,8,5010.0,15.0,0.018271,0.003491
86,-1,4300,TOMATOES,4995,10,4994,20,NaN,NaN,5008,...,4995,10,4994.0,20.0,5008,10,5010.0,20.0,0.079836,0.039688
89,-1,4400,TOMATOES,4995,8,4994,15,NaN,NaN,5008,...,4995,8,4994.0,15.0,5008,8,5010.0,15.0,0.028845,0.008789
90,-1,4500,TOMATOES,4995,9,4994,17,NaN,NaN,5009,...,4995,9,4994.0,17.0,5009,9,5010.0,17.0,0.036263,0.036263
93,-1,4600,TOMATOES,4995,7,4994,17,NaN,NaN,5009,...,4995,7,4994.0,17.0,5009,7,5010.0,17.0,0.025807,0.025807
94,-1,4700,TOMATOES,4995,10,4994,17,NaN,NaN,5009,...,4995,10,4994.0,17.0,5009,10,5010.0,17.0,0.028873,0.028873
97,-1,4800,TOMATOES,4995,7,4994,21,NaN,NaN,5009,...,4995,7,4994.0,21.0,5009,7,5010.0,21.0,0.021315,0.021315
98,-1,4900,TOMATOES,4995,10,4994,16,NaN,NaN,5009,...,4995,10,4994.0,16.0,5009,10,5010.0,16.0,0.006570,0.006570

In [7]:
price_cols = ["bid_price_1", "bid_price_2", "bid_price_3", "ask_price_1", "ask_price_2", "ask_price_3"]
volume_cols = ["bid_volume_1", "bid_volume_2", "bid_volume_3", "ask_volume_1", "ask_volume_2", "ask_volume_3"]

def outlier_remover(row):
    if pd.notna(row["bid_price_3"]):
        row["maker_bid_price_1"], row["maker_bid_volume_1"] = row["bid_price_2"], row["bid_volume_2"]
        row["maker_bid_price_2"], row["maker_bid_volume_2"] = row["bid_price_3"], row["bid_volume_3"]
    else:
        row["maker_bid_price_1"], row["maker_bid_volume_1"] = row["bid_price_1"], row["bid_volume_1"]
        row["maker_bid_price_2"], row["maker_bid_volume_2"] = row["bid_price_2"], row["bid_volume_2"]
    if pd.notna(row["ask_price_3"]):
        row["maker_ask_price_1"], row["maker_ask_volume_1"] = row["ask_price_2"], row["ask_volume_2"]
        row["maker_ask_price_2"], row["maker_ask_volume_2"] = row["ask_price_3"], row["ask_volume_3"]
    else:
        row["maker_ask_price_1"], row["maker_ask_volume_1"] = row["ask_price_1"], row["ask_volume_1"]
        row["maker_ask_price_2"], row["maker_ask_volume_2"] = row["ask_price_2"], row["ask_volume_2"]
        

    return row

In [61]:
dir_map = {"buy": 1, "sell": -1, "bot_trade": 0}
tom_trades["position"]=(tom_trades["quantity"] * tom_trades["our_direction"].map(dir_map)).cumsum()
tom_trades.head(60)

C:\Users\malac\AppData\Local\Temp\ipykernel_23140\1394586428.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,timestamp,buyer,seller,symbol,currency,price,quantity,our_direction,position
0,2900,SUBMISSION,,TOMATOES,XIRECS,4998.0,3,buy,3
1,3300,SUBMISSION,,TOMATOES,XIRECS,4997.0,3,buy,6
4,10200,,SUBMISSION,TOMATOES,XIRECS,5014.0,2,sell,4
5,13200,,SUBMISSION,TOMATOES,XIRECS,5010.0,5,sell,-1
6,14700,,SUBMISSION,TOMATOES,XIRECS,5009.0,3,sell,-4
7,14800,SUBMISSION,,TOMATOES,XIRECS,4997.0,5,buy,1
8,17400,,SUBMISSION,TOMATOES,XIRECS,5009.0,5,sell,-4
9,18800,,SUBMISSION,TOMATOES,XIRECS,5005.0,5,sell,-9
11,24600,SUBMISSION,,TOMATOES,XIRECS,4989.0,2,buy,-7
12,27300,,,TOMATOES,XIRECS,4993.0,5,bot_trade,-7
15,30900,SUBMISSION,,TOMATOES,XIRECS,4983.0,5,buy,-2
17,40000,,SUBMISSION,TOMATOES,XIRECS,4991.0,3,sell,-5
21,44300,SUBMISSION,,TOMATOES,XIRECS,4979.0,2,buy,-3
22,48000,,SUBMISSION,TOMATOES,XIRECS,4990.0,5,sell,-8
23,48700,,SUBMISSION,TOMATOES,XIRECS,4994.0,2,sell,-10
25,52200,,SUBMISSION,TOMATOES,XIRECS,4992.0,3,sell,-13
27,58800,,SUBMISSION,TOMATOES,XIRECS,4993.0,4,sell,-17
28,59300,,,TOMATOES,XIRECS,4984.0,2,bot_trade,-17
29,59400,,SUBMISSION,TOMATOES,XIRECS,4991.0,4,sell,-21
32,65300,SUBMISSION,,TOMATOES,XIRECS,4984.0,5,buy,-16
33,66600,SUBMISSION,,TOMATOES,XIRECS,4982.0,5,buy,-11
34,67700,SUBMISSION,,TOMATOES,XIRECS,4981.0,5,buy,-6
35,75000,,SUBMISSION,TOMATOES,XIRECS,4996.0,2,sell,-8
37,83600,SUBMISSION,,TOMATOES,XIRECS,4981.0,4,buy,-4
38,85400,SUBMISSION,,TOMATOES,XIRECS,4978.0,3,buy,-1
39,86900,SUBMISSION,,TOMATOES,XIRECS,4978.0,4,buy,3
40,89300,,SUBMISSION,TOMATOES,XIRECS,4987.0,2,sell,1
43,91300,,SUBMISSION,TOMATOES,XIRECS,4986.0,5,sell,-4
45,96100,,SUBMISSION,TOMATOES,XIRECS,4989.0,4,sell,-8
46,96400,,SUBMISSION,TOMATOES,XIRECS,4989.0,4,sell,-12
48,101700,,SUBMISSION,TOMATOES,XIRECS,4994.0,3,sell,-15
50,105700,,SUBMISSION,TOMATOES,XIRECS,4993.0,2,sell,-17
51,107100,SUBMISSION,,TOMATOES,XIRECS,4981.0,4,buy,-13
52,108000,SUBMISSION,,TOMATOES,XIRECS,4980.0,3,buy,-10
53,110600,,SUBMISSION,TOMATOES,XIRECS,4999.0,4,sell,-14
54,111600,,SUBMISSION,TOMATOES,XIRECS,4999.0,2,sell,-16
56,120800,,SUBMISSION,TOMATOES,XIRECS,5002.0,3,sell,-19
57,122900,SUBMISSION,,TOMATOES,XIRECS,4990.0,4,buy,-15
58,124300,SUBMISSION,,TOMATOES,XIRECS,4994.0,2,buy,-13
59,128700,SUBMISSION,,TOMATOES,XIRECS,4989.0,2,buy,-11
60,130100,,SUBMISSION,TOMATOES,XIRECS,4999.0,3,sell,-14
61,134900,SUBMISSION,,TOMATOES,XIRECS,4986.0,4,buy,-10
62,139500,,SUBMISSION,TOMATOES,XIRECS,4999.0,3,sell,-13
64,143700,,SUBMISSION,TOMATOES,XIRECS,4998.0,3,sell,-16
68,153600,SUBMISSION,,TOMATOES,XIRECS,4983.0,2,buy,-14
69,155800,,SUBMISSION,TOMATOES,XIRECS,4997.0,5,sell,-19
70,155900,SUBMISSION,,TOMATOES,XIRECS,4985.0,5,buy,-14
71,156800,SUBMISSION,,TOMATOES,XIRECS,4984.0,4,buy,-10
73,160300,,SUBMISSION,TOMATOES,XIRECS,4991.0,2,sell,-12
74,161500,,SUBMISSION,TOMATOES,XIRECS,4989.0,5,sell,-17
75,161600,SUBMISSION,,TOMATOES,XIRECS,4977.0,2,buy,-15
77,164100,,SUBMISSION,TOMATOES,XIRECS,4989.0,2,sell,-17
78,165300,SUBMISSION,,TOMATOES,XIRECS,4980.0,5,buy,-12
79,169100,SUBMISSION,,TOMATOES,XIRECS,4982.0,2,buy,-10
80,171400,SUBMISSION,,TOMATOES,XIRECS,4982.0,3,buy,-7
81,172200,,SUBMISSION,TOMATOES,XIRECS,4994.0,5,sell,-12
82,172600,SUBMISSION,,TOMATOES,XIRECS,4983.0,2,buy,-10
83,174600,,SUBMISSION,TOMATOES,XIRECS,4997.0,2,sell,-12
85,176900,SUBMISSION,,TOMATOES,XIRECS,4986.0,4,buy,-8
86,177300,SUBMISSION,,TOMATOES,XIRECS,4985.0,3,buy,-5